apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: ${NAMESPACE}
  labels:
    app: zipkin
spec:
  type: ClusterIP
  ports:
  - port: 9411
    targetPort: 9411
    protocol: TCP
    name: http
  selector:
    app: zipkin

